### ISSUE TITLE
Server crashes when the game starts. 

### ISSUE THREAD

**Issue by ItzJNTZ** [TheNewHEROBRINEX/Murder#25] opened 2018-01-16 22:55 UTC
For the first 10- 20 games everything is fine. Then after playing a few games the server crashes when the game starts. 

PocketMine-MP Crash Dump Tue Jan 16 22:41:12 GMT 2018

Error: Call to a member function getPluginManager() on null
File: src/pocketmine/entity/Entity
Line: 1968
Type: notice

Code:
[1959] 	}
[1960] 
[1961] 	/**
[1962] 	 * Closes the entity and frees attached references.
[1963] 	 *
[1964] 	 * WARNING: Entities are unusable after this has been executed!
[1965] 	 */
[1966] 	public function close(){
[1967] 		if(!$this->closed){
[1968] 			$this->server->getPluginManager()->callEvent(new EntityDespawnEvent($this));
[1969] 			$this->closed = \true;
[1970] 
[1971] 			$this->despawnFromAll();
[1972] 			$this->hasSpawned = [];
[1973] 
[1974] 			if($this->chunk !== \null){
[1975] 				$this->chunk->removeEntity($this);
[1976] 				$this->chunk = \null;
[1977] 			}
[1978] 

Backtrace:
#0 src/pocketmine/entity/Human(728): pocketmine\entity\Entity->close()
#1 src/pocketmine/entity/Entity(2111): pocketmine\entity\Human->close()
#2 src/pocketmine/level/format/Chunk(776): pocketmine\entity\Entity->__destruct()
#3 src/pocketmine/level/Level(2713): pocketmine\level\format\Chunk->initChunk(pocketmine\level\Level object)
#4 src/pocketmine/level/Level(2344): pocketmine\level\Level->loadChunk(integer -39, integer 26, boolean 1)
#5 src/pocketmine/level/Level(2982): pocketmine\level\Level->getChunk(integer -39, integer 26, boolean 1)
#6 src/pocketmine/Player(945): pocketmine\level\Level->populateChunk(integer -39, integer 26)
#7 src/pocketmine/Player(1728): pocketmine\Player->sendNextChunk()
#8 src/pocketmine/Server(2542): pocketmine\Player->checkNetwork()
#9 src/pocketmine/Server(2279): pocketmine\Server->tick()
#10 src/pocketmine/Server(2154): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1742): pocketmine\Server->start()
#12 -----------------------------------------------------------------------

PocketMine-MP version: 1.7dev #627 [Protocol 160; API 3.0.0-ALPHA10]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT NS306121 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) AMD64
PHP Version: 7.2.0RC6
Zend version: 3.2.0-dev
OS : WINNT, win

Loaded plugins:
AllSigns 1.0.6 by  for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
AlwaysDay 1.0.0 by Sean F. Quinn <sean@esqew.com> for API(s) 3.0.0-ALPHA10
AlwaysSpawn 2.2.3-4 by Philip Shilling for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
MagicTelePortal 1.3.2-4 by aliuly for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
Murder 0.9 by TheNewHEROBRINE for API(s) 3.0.0-ALPHA10
DevTools 1.12.8 by PocketMine Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
Slapper 1.3.7 by jojoe77777 for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
VoidHUB 1.0 by CookieCode for API(s) 3.0.0-ALPHA10, 3.0.0-ALPHA9
Worlds 1.0.13 by  for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
BlockSniper 2.3.0 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwtv40aS/isdOcDagSiJkmzZynmwju3JeNcPnaXZAS4MBi2xJTHma9ikbSWY/35fVTcpSn5k
Npu9LHAZBGuxH9VV1VVfVVf3/tLIg0g1hu6+e+D2u/1Bt9kIpc7PsyzJGsNfGvkqRXcjTvJgphrN
RqS0lgtqOpVhKPJESBGpaKoyMS/iWR4ksViofBQWiyC+kjHGZrt7Aq1xEYYgMMeft0FIFNKlzIbt
9vmw/V6rjBp1+2831yeTdyfX/9P+XkZqrLJ7len25LTfPxx0+od9d3AwwH/97sF+v9/pt0fJ7E7l
V0GsnKtRiyi2dTZrp9wcobmt4jzIV+1z/oMRKTFhGHhtJEaFaIRqjg4Om408k5B/+ENjpyOen/au
iGS8O+ge7g3FutfzTLfnGbLOm1mYaLW7B/o7rniNg92u67ovEOPFNmh1t2mF6l6F7XmSRTJvny6L
+G4XmvsV5j5+9JXOs2KWG6q956le0v/udgdub4sed3ueWdXzeFnnTRAHueHgmbFMSyTTn9Qs5zX7
r67Z6/efX5P7nTdhIn2zVhDnCtYnnN5RU5Qf3YOmmCZJqGQsXF5u/9Xljg67ry4HW/+nVjvYXm0U
yhVc5Ki//+o6aZIWoczVq4vxCoMXVnCfmqbpcd5oFfvX6tFKwlQOt6kYV9zt7ve7L1CZLdXs7lrl
D0lmiRy9RKQ7ONoiYnqcN4AZO9ntvDTb3e+/MnuUJTOAVJJZMu4LZNzBE0lKMjqXmXUA94lfrRFn
d3+/9wKFjx9nSWwd6Tup1SlAVV/CNLFPxtSbG/OKPAi1513JIL5MFovaKBAJ4oU4H3pehZKeV8Gk
59Vw0vNeBErP+x1JpYzuGGNU1BO/M4TvEuxl6lMRZGrXcv1/EyzWIyhS7DV+/NxsqH9fLPwnwxCY
MapvDOcy1KrZmCW+Itbco/0jUPLyz5iAoR18mF8uN7e/+cZ8dvlTfCNOKXRokS+VMAsKGftinik0
yjyX8GYfezBXmYrhTy0zvWenm69+SezDye31xfX3Q8FMB0QiU6KICy2noRJynkMn+TLQYim1mCoV
C/WoZkWu/K8MqX1Lqm0+D/gzLaZhMFsr04a7X8yYAY/x8mC++9XXRNzGQ78ccGgHeLnt1tY7n24K
pmILz++hit1YPRg5VmdKp/IhNs1MY2/vW0P7aJu2WVocC8+D2yszbFDtw8DdnuAb4m+zJDoJw11L
eNDdHgeNjWkgE//hRzusVxHuVxOgiJIZAnLx1TFxQ7ZmNTLYr8au+TYhOlNRcq9s4mFEtSsdvDBH
lMTtuEE1ztjggNTf+Pxn6vRn6vRn6vRn6vRn6vT/LXVqNhYqVpkMKUGJJZUZGhtkoAFaFZEdPW5r
4Kt7NE2LIPQbw4PuANlOluTJLAEF96DTbMg0wMheq9PqOCeXo3cnbgcTFkGO1s4X/sOETN6FwZTm
tI5a1FBY7j4EsZ88aHE9EdfjXufA7brioOUKZkkMDjqu2C3HGJWJbqdzKG67YpwjfZKZL879gHMV
6keaKEZydgcAEydXZ8iXINIyxUqDVrfVuT09QMPPQBCWCi2OUQHGfEw0MXRxfT1BA388IO+rMkBN
SkXeMA4W5rcVoWra1G2nRUvJIl8mGYb/8KNV5g91bQ4wpPZ5uPl5tPkJ1YOIiinBA/+U8zQbvkoh
jV1AJ/P8rN4QScpcG7rI7qXnId/SxKnn1XimEERmcjOefLi5vTxD04Oa6iBXNpk4CR/kSp/J1YbM
Zdu20J0NoRtjCiZvW+K/iyCOxX9pfP5V6U/qoTVLojeNZ5Xy2+VkyiSd5c5gFMPZr0m6zPNUw2Ur
5taicy74RHjTWhe/C3vqOf1NBYyWQRikYow/OFUsGn+kGaTMi7askD2QIJwTI3Qz3q/VNJ6c3E7e
j56Ywynyg+xSLhY1jazbNs3B3TaHS8T+2L+ZX52Ozp9Xxe8mbMXTU9FetwCA27KYkgm06+y210JC
C1dyEcwmKlSjJMs38Ha7Z1MjwJxtC5FhUISrP9QwDAueF+WpcZkvwYWrIiOt1iQ3DXWBAfebwk6W
6lo9vDu/vfnu9uL6/PcGgC3yEIZ5Kv9+qWhn6n6CRLiO8lXTloV3W4dbDl/FWzFRMvpD97Vk2vNq
7L/i38+4wFqcdkUDGhqHMk03dr9s2bb3waZ6fkp+StSA/v2b/V8bfr7Mnp8RfM1ouxQNcv8jCfx3
77+ryV22bAXCTalPk+QuUKdUOnrJ4rcs4LeiXrWQ51nOvtyjPyRZ6NeN3jZsx3i395+W2Twwo55X
Mfyrsn4XwrDHcbBpxPXWzdDe295SHvouyYKfE86jxshGVZbfi92/lj/pwHG6zALtjLIgUuihv4W+
/McfgAqNq9UoTPLGWncbEnheTfYvDZmNz5QdywzKy1VpC6bk18JBApSoMomBO6PqS5wm8TxYCKrE
epkX70wKJf5GJYcD4R4N97vD3pH4/mqCPN89pAG2hEg7dIwzUqvntrrQAnVFSe4fG2gXVysNHla1
GUG6Pd52pIjMx+5Rt9elxiSmcq8TwWeOk/mcmriaYVY02VHVRgXp47PztyfvLyfUusAYnmn4kY9O
ygUGfeyaFWm6Q4cqxQXV4/0Ot8s4Top4puxwR86WARaIVJzr44QXfFhCyU4Y6Lxky2y286mAnHaQ
bcpwgLct9LOVIuOFT/jH3/A/rBeGyYMzD4PFsiJneJNxEMlQbzZGybRqmScZ+KwEta04jvqzJKu+
0/u0/OkH83kwK8J8deyyjvhMmieZo1WeI/PUx2uFaqV8/oRrJY6W98rKcR+oB8eH9BJqOmZLeJwm
jw65oB1C57bqNNxaRSFZmiC0EzM2sgLL0smQbE1ADrFxGIbtCSQMWomSL66hU30+iblQL3Mxo53K
xVSJIJ6Fha98/BBPbJxojRP4eDInAts0tZyrpkjQk2kiKaaZkndilRSZpSWCuYB+g3nAK0C1GSwG
SRkII6WpyLV9NZfQrRYPSfyXXFBkkpkg7UUQlmrqK+KQS/8s98NSxaJIF5n0QaDlxeQHhtjQi8XO
ZJkp2BmawEUo40UhF0rQNQerzPqMDvANhECq+DMrlaaeUhHNSLE5ETqvDlRx6yG4A6r4gWwl2aJN
X+1LbOzHZP7xYnzz8aB35HQ/0jyosSI0FB7QbeE1aKEPS0W6owsfKv8JuvwxpRZsUyZjTdVG33Sz
NplT8IFfKuctxTmfigNLYHPImxyBsLHt9ZJ8x4N2vSxyPyFHMBdOxIwtP5hbB8PWCXmVIBfloo8p
E4j7QOK8S1gUC/ZVx/YMBaE0TRwvMU+SleoE3NhVzFZJS0gUdFsERIchsHQnowuMRADySU/rDgds
TcHUmvw5o0JJh26ZyFUFzBUWQaxOV8LaEYZbDKl612rY+YCjIjYTJiV9upvSxvKITapegh2JCMyw
JQK6ZiJ9QOnqUyH5em4R3GPsvQwB8rt2SSD7Hoib9YBdivDYwW5SKXGIXlr5uuBbPbjTiV7Fs4nU
d4JqtXCgFvW/p6sfss9SSBq1zBLAKkwCo3VTcFYgLPzAZJtQQwStaYrqrBaEMmqLihieQ0OY9phN
BvLAubLkEfiYK6gA4rCpxxVrpFXDzsWcPJQvJOGJTRHkf6H7yYxn+YrQn61wa67YhQTYZ9EljbAM
jpVyyJTIWwl4sxX76vdhMoViKbIL0wzri4KcPD5SCzld5WBIjA0rHV484BtB4+mQ6SFgxljZgoKC
oVPqX5tLyQDmAphSdA9HVOiWslzRbD+EKdhoFwnkSO7tdSPWWTCTDjM2FB2PoYJROQfUSP8/nH3K
jl5hngLfv8S8zpOU17dQVfFjqWkBl6IADpSx3NCaJUtup9s3XLFjfGBrsczpv/zr7M0yqZfMD3mR
mBUIRDECkb0+JvRIDL/GUClwVaPV4wzxXK/FYVe+mZwPxeTdxVhcXlxdTABko8uL87EYnd8KJJV/
P79tCgwSkxuMOhcf3t1cnovR7c3p+Xjc2vKLF3QxUlmQcGgmXNIkHd/wlKqosMeF2gG7Pvkbj3CA
DcqgDoe0JIaMQCvYEMn6kokZ00KOFnK0I9wzwzxOPogGkGiNagaaaYUbglOK9jy89XQwmYDN67Ff
qZpRUmB0SryaDTVzKwFgVSrVazF7HSun3nuWISt1z0i9kNkUvuDMkjA0eSqhzbNaZdciVuwcYecA
xyIZF5x+1LlAalbA8PaaJT5uWZ41PRNj5nNQMpJGa5driRsT/I2NIzgnRehXnASA04dYrHknJxYp
sw4JDzodI6TYecuw8CRQsLGY2ZVU8yyJynhDc22/UzfF2qZCCrt327bwjAHVjWFcZom0RVnChdnS
Zv0iSk2+YvI22+5Qu9mfMxphRzPHzF7JN74Q4ODS8hmVImAhmIH8PQxK60KR++dL7NKizC8Jl2it
NUvNcuNMeLRpJLHGA1/SDh2L+AGDNmyfypTacBSOkFPQWVmUiT7tmzBnIsPAWpnkFlaD7BhPzQmZ
dcrMmBcWlPAWiKN9u0VnienYNl1KBgjSDG0aWjqJoWOH1QTixMKZ0YsdK9IZOOBkEHkS6QtMmezD
kEglnTuEmWEEWwuFaaxBI0S5KA2tMjrojKrPJc3XyLxmb14cmxvvKvGHL4Umj5rKHGdQSmOZV01X
9cIGDYYsc6yxvSZWTFWVUXGw2qlvStlDUJmtcqLdFI5b2y/aK17WyUtWAMT7BwaH15kanxQpTfKN
zHQE4CyW5qLR8tQS73C8heEc4yQFTz8dvW9iLjiYwokeAh/mzTGfEbEi7zD5oRjYtHKdcGpWTG1o
S5z4Pr2oCudtHBFNDuwrmKtdCEsKqpiQPdXcrYphNVq1LPv8kdCKkmgZNg0U0sL23rMlgC2KUYoy
xfejeFTmmesTH6XQNOkB0dGj416cOvazntHjcK6mxcJsf2KjjKBcI2M3sDGeUmWCa7oobVW9miyC
M+B0mbaCOCA2XJatHGGc4YPMYopwtZl0CLYxjahYAsATRFoSZj0ykrDmCFuakxKzIqbn8gQL/EyH
IAKUy/BIy0HG2Anmjm1bn4IAcW+ES7m4Tbzo0MXylwcubU7KqjyIedbWhiyWPUZp0QY25QU8or2Y
GdsBI75e76AXG8gamkNxgsMYWWp5ZFXlcYxhzZe5FFreW+SkkkdZBaKuin8JyQEGSuZGqxDHPEEs
c2A+W8CcOBPRKRIvzkziZEY3jjwTxnMFfc4kWQ49N7MnNcJ7Vp6pC5U9Zjm9BoyyRrNRLlDl2VGY
l1OmUMJDLS4U2p5lZ7D+nKHBTnHMlKFIocL7IOQ8dsOSZ4h4wGZLjj2MExzISh6Vk1d1OzYhoWhh
8hxSGFWQqN0mN6UeN5rL1NGcMsfKphtTqVVtsV0XIPLMKk3RRYf7XIfKZ609BjSt6lywJU2IMhUt
bHVQKEC4WY+2zyiLy0PrupFfhhSKtZwG83WtoW3p1BzbhA0LjaWDW2Xak0ZMug+3Q26zHLVRcXu2
ysVH3ZMogVPyEZZjOsExo34pG2mFmKQzPoyafnIQFju3HJFrU9lyYmVKN1NlSE3VnOCbK5EcS5el
75C7cH1yI7QbyWmZUvIr+SjkNpupeWqFtSrlb3LYeZZFmYGOz1UZdl8waqfaTTac9Ag7qLrqFCnc
WNXQYUah22wblYpqAHXGC02p8K4FlRlJiwbpYIdA/0hYsYQpTZQ5Ak+piyx2HJjmjljg9KbXSlnX
Pkq9tJ4qxmLggwz4dPepUAaUsR92Pnswtzs6+BlGffibqJXPAoma/U3xd4uwF7NzOanBU3Jfwsih
KDN5dmhTNRoaJ6YCFx9bTauJ23a/6aVDWeNaBwfyE4dKjpstFdJttCJaBfE8We8o8M0x9c1y3DKh
jWUmWmkUIbpx6UbGSbyK6NxFIYTqhDNd8UwHSdst1t3MO8cIuVhkOLibcFzVBClxpfe9d1uCMW9w
+puzG3qOZsOhSdQZXh6UyfaloOfWtKBmtivuualVq6gjWaz0bayad2Rbl9hC0zuswrGNp+v8lVuT
msJwCIjJJnzC+SSl6NMEwqVL2UQzpKfSc15miSk/i0fe7xBWxRShaZCN8gVtMuSq0RL27q4W/Qvk
wjo3YFfCiqVGG226S/rbO2sErG8t0pIqJtqQTxRpeJmq0U4SqNJqnDfZOWUhtVWRtx11+qUKX00p
LLCbzTTGXyvQlOXlPMiNGstSzNK2MbrQScsm8xZeqNKLM5LPKW0wr+jgIAQpTDJHaFXLwpicBdIy
eZBhgFhoNHT+KKM0tB+UiIE/u0XDcq+4CxZKBbKh+IETI0TAJlfMfiSK5pq3TEPqlywsAVXxMrqn
4PpEeevEmexz0YyzJQ6xmpN2PudiXwIwavOPGuu8KjPAvwRdXFHQ4MC2Xm0o3l6eTIbdbwfN/aNH
t9l77DW737rf+kgTDBLv5pnCB1Dz+LBjANt89ff3+E5LPeYqJoXwVfwpYuHm88XpDNnScrONbjvo
NeRWq/3/z9SbiizcbCHD3myZB2Gutkgtoq1HlEtAXfXUIYCJ3G/2/6Tte4EDHhFNzX3N5iBt33Bu
tqazbZFTW/vhV5vVu9VbNbfn9y2qDGF6uxGBOtpsG48uNxuilf4U8uNQ+0vs03uHLr0SFQ5dSe93
+p0Bfn59gd2f9o4Ojvb7Sk27vusfKX9w1OlOD6dSdXuDafdwMO+6Eu3ia9DOkzsVI8htKXYl+d4S
360uvU0NUvOwaL/l0qd5Nlsbj4bHaHsLExKs2+n0XLdL7wRg4rHWW6OeTBst2WDKpdfI/5FjOT/z
5kdctMmfP/8vNH19aA==
===END CRASH DUMP===

**Comment by ItzJNTZ** [comment] 2018-01-16 22:58
World crashing

[NewZip (1).zip](https://github.com/TheNewHEROBRINEX/Murder/files/1637109/NewZip.1.zip)

**Comment by TheNewHEROBRINEX** [comment] 2018-01-17 06:55
Does this happens also if you teleport yourself to that world?

**Comment by TheNewHEROBRINEX** [comment] 2018-01-17 07:01
Ok yes I can reproduce the issue

**Comment by ItzJNTZ** [comment] 2018-01-17 09:08
Yes it happens if i teleport to the world aswell. Whats wierd is that it everything is working perfectly for several games then this issue occurs.

**Comment by TheNewHEROBRINEX** [comment] 2018-01-17 16:05
Duplicate of #22

**Closed by TheNewHEROBRINEX** 2018-01-17 16:05 UTC
