### ISSUE TITLE
Every time a player joins a match the server crashes.

### ISSUE THREAD

**Issue by WEATHERCRAFTYT1** [TheNewHEROBRINEX/Murder#52] opened 2020-06-29 15:22 UTC

**Comment by WEATHERCRAFTYT1** [comment] 2020-06-29 16:48
PocketMine-MP Crash Dump Mon Jun 29 00:42:46 UTC 2020

Error: Nesting level too deep - recursive dependency?
File: plugins/Murder_dev-77.phar/src/TheNewHEROBRINE/Murder/MurderArena
Line: 295
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Murder v0.9

Code:
[286]     public function spawnEmerald(array $espawn) {
[287]         $this->getWorld()->dropItem(new Vector3($espawn[0], $espawn[1], $espawn[2]), Item::get(Item::EMERALD));
[288]     }
[289] 
[290]     /**
[291]      * @param Player $player
[292]      * @return bool
[293]      */
[294]     public function inArena(Player $player): bool {
[295]         return in_array($player, $this->getPlayers());
[296]     }
[297] 
[298]     /**
[299]      * @param Player $player
[300]      * @return string
[301]      */
[302]     private function getRole(Player $player): string {
[303]         return $this->isMurderer($player) ? $this->getPlugin()->translateString("game.murderer") : $this->getPlugin()->translateString("game.bystander");
[304]     }
[305] 

Backtrace:

PocketMine-MP version: 3.14.0 [Protocol 407]
Git commit: 461bc94236ba1f3504b6f5a20eba9df80ef9a7bd
uname -a: Linux 2259d831-8eb2-4dce-aa98-775e9371ee01 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64
PHP Version: 7.3.19
Zend version: 3.3.19
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
- ocramius/package-versions 1.5.1@1d32342b8c1eb27353c8887c366147b4c2da673c
- pocketmine/binaryutils 0.1.11@e8cb65db1b7998eebb739b124f2a989fe87366eb
- pocketmine/callback-validator 1.0.1@4aef6bb25f97d0b830ba0b4f66834b1a9c86fc9a
- pocketmine/classloader 0.1.0@4ccdb30e48f030bfcad04bb0a208d198ec631993
- pocketmine/log 0.2.0@e59bedb5d4bbeb9a26647cb7c367cb2fa72addfa
- pocketmine/log-pthreads 0.1.0@9bbcef398b01487ab47c234a6a7054722abbe067
- pocketmine/math 0.2.4@b1c28b236df8b795d7b06cf8421f9962b12ac410
- pocketmine/nbt 0.2.14@b31dca98443328c4bab76dc1b84c1473c79be20e
- pocketmine/raklib 0.12.8@9fea763ffc922db083e4528d4acd0b13d0ea83a4
- pocketmine/snooze 0.1.2@88420da3d9335dbcb3ee2decfd5e5453d057dcdf
- pocketmine/spl 0.4.1@ff0579a0be41bbe65d3637607715c0f87728a838
- doctrine/instantiator 1.3.1@f350df0268e904597e3bd9c4685c53e0e333feea
- myclabs/deep-copy 1.9.5@b2c28789e80a97badd14145fda39b545d83ca3ef
- phar-io/manifest 1.0.3@7761fcacf03b4d4f16e7ccb606d4879ca431fcf4
- phar-io/version 2.0.1@45a2ec53a73c70ce41d55cedef9063630abaf1b6
- phpdocumentor/reflection-common 2.1.0@6568f4687e5b41b054365f9ae03fcb1ed5f2069b
- phpdocumentor/reflection-docblock 5.1.0@cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e
- phpdocumentor/type-resolver 1.2.0@30441f2752e493c639526b215ed81d54f369d693
- phpspec/prophecy v1.10.3@451c3cd1418cf640de218914901e51b064abb093
- phpstan/phpstan 0.12.29@9771daaf6b95c6313b908d0bcdee0afcd51f838a
- phpstan/phpstan-phpunit 0.12.11@ab783a8ea634ea23305a8818c4750603e714489b
- phpstan/phpstan-strict-rules 0.12.2@a670a59aff7cf96f75d21b974860ada10e25b2ee
- phpunit/php-code-coverage 8.0.2@ca6647ffddd2add025ab3f21644a441d7c146cdc
- phpunit/php-file-iterator 3.0.2@eba15e538f2bb3fe018b7bbb47d2fe32d404bfd2
- phpunit/php-invoker 3.0.1@62f696ad0d140e0e513e69eaafdebb674d622b4c
- phpunit/php-text-template 2.0.1@0c69cbf965d5317ba33f24a352539f354a25db09
- phpunit/php-timer 5.0.0@b0d089de001ba60ffa3be36b23e1b8150d072238
- phpunit/php-token-stream 4.0.2@e61c593e9734b47ef462340c24fca8d6a57da14e
- phpunit/phpunit 9.2.5@ad7cc5ec3ab2597b329880e30442d9054526023b
- sebastian/code-unit 1.0.3@d650ef9b1fece15ed4d6eaed6e6b469b7b81183a
- sebastian/code-unit-reverse-lookup 2.0.1@c771130f0e8669104a4320b7101a81c2cc2963ef
- sebastian/comparator 4.0.2@266d85ef789da8c41f06af4093c43e9798af2784
- sebastian/diff 4.0.1@3e523c576f29dacecff309f35e4cc5a5c168e78a
- sebastian/environment 5.1.1@16eb0fa43e29c33d7f2117ed23072e26fc5ab34e
- sebastian/exporter 4.0.1@d12fbca85da932d01d941b59e4b71a0d559db091
- sebastian/global-state 4.0.0@bdb1e7c79e592b8c82cb1699be3c8743119b8a72
- sebastian/object-enumerator 4.0.1@15f319d67c49fc55ebcdbffb3377433125588455
- sebastian/object-reflector 2.0.1@14e04b3c25b821cc0702d4837803fe497680b062
- sebastian/recursion-context 4.0.1@a32789e5f0157c10cf216ce6c5136db12a12b847
- sebastian/resource-operations 3.0.1@71421c1745788de4facae1b79af923650bd3ec15
- sebastian/type 2.1.0@bad49207c6f854e7a25cef0ea948ac8ebe3ef9d8
- sebastian/version 3.0.0@0411bde656dce64202b39c2f4473993a9081d39e
- symfony/polyfill-ctype v1.17.1@2edd75b8b35d62fd3eeabba73b26b8f1f60ce13d
- theseer/tokenizer 1.1.3@11336f6f84e16a720dae9d8e6ed5019efa85a0f9
- webmozart/assert 1.9.0@9dc4f203e36f2b486149058bade43c851dd97451
- pocketmine/pocketmine-mp 3.14.0@461bc94236ba1f3504b6f5a20eba9df80ef9a7bd

Loaded plugins:
WorldGuard 1.1.6.3 by Chalapa for API(s) 3.0.0
Murder 0.9 by TheNewHEROBRINE for API(s) 3.0.0
RankShop 0.1 by LousWiteMC (Phạm Nghĩa) for API(s) 3.0.0, 3.11.0, 4.0.0
TopKills 1 by  for API(s) 3.0.0, 4.0.0
WarpsPro 1.3.0 by nikoskon for API(s) 3.0.0
WorldLoader 1.0.0 by JackMD for API(s) 3.0.0
ProfileUI 4.2.2 by Infernus101 for API(s) 3.0.0
MOTDShuffle 1.1.6 by TheDeibo for API(s) 3.0.2
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
PureEntitiesX 0.6.6 by milk0417, RevivalPMMP for API(s) 3.9.0
Scoreboards 1.0.2 by Twisted for API(s) 3.0.0
TopMoneys 2 by moch for API(s) 3
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
BetterNick 1.0.0 by HimmelKreis4865 for API(s) 3.0.0
Dragons 1.0.0 by VixikHD for API(s) 3.0.0
Report 0.1 by ConstructStudios for API(s) 3.0.0
MapImageEngine 1.1.3 by FaigerSYS for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
1vs1 1.0.1 by VixikHD for API(s) 3.0.0
ScoreMC 1.3.5 by Array for API(s) 3.0.0, 4.0.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
Rewards 4.0 by Wertzui123 for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
AutoClearLagg 3.1.0 by Twisted for API(s) 3.0.0
DevTools 1.14.0 by PocketMine Team for API(s) 3.11.3
ColorMatch 1.0.0 by  for API(s) 3.0.0
EggWars 1.0.0-beta1 by ANDREAX22 for API(s) 4.0.0, 3.0.0
Festival 2.1.2 by Genboy for API(s) 3.0.0
CustomFFA 1.2.3_BETA by DragoVND for API(s) 3.0.0
JoinUI 0.1 by  for API(s) 3.0.0, 3.0.2, 4.0.0
AutoUpdater 1.0.1 by  for API(s) 3.0.0
BetterVoting 2.0.0 by Twisted for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
TNTRun 1.0.0 by BeckenPlayZMCPE Fixed MCCreeperYT for API(s) 3.0.0, 4.0.0
XGTShowPlayerHP 1.0.0 by XGDAVIDYT for API(s) 3.12.1
SynCore 2 by MrGalletaYTPM for API(s) 3.0.0, 4.0.0
MailPlugin 3 by HmmHmmmmm for API(s) 3.11.0
ParticlesUI 1 by Giings, xSoapers for API(s) 3.0.0
DEVirion 1.2.7 by poggit, SOFe for API(s) 3.0.0
SurvivalGames 2 by Keanu@XvEnOm for API(s) 3.12.0
KillRewards 1.2.0 by Dim9999 for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNXAlz3MaV/isoyrWRXJwh7mNcylImKVmJKHJJ2nLicakaQGMGJq7gIDlK+b/v97obGGAoS7TE
bK0qMQcN9Ot3fu+9xvHvvaSsc9a+v+F1k5bF3sLa32vTnO8tDCewrMCwXHd/j9d1We8t/r3Xbiqc
2jt5f3JxcXaxt7+X86ZhKxp7y5s2LVZaxm94prVlqcWcV9pMq3nUgfgNx0DFi5gX0ea/MTVJM5pX
Zd0qLZqD066Oef0+5jczz5tXa1YfNHV0cLXmb/ntDycXZ99fvH57oi5Tf17UvGAglaUFSJmB8/u+
ovc+LW7K7IbnvGixSJyCi3avP4sRSQAjURlzEs30XQxr+Fd1YZZGWtIVUQudaE3FbouTnNcsi5+y
umYb7RsuBp9p/wYF0/fUTPr3TbtOm9lfV7x9V9aY8Gz217guq9ctz58W/Fb7CYyUtfVUkfhF/3W/
J/eLMfpt/vpsX6NZiwVoPZW/Tk5PLl68OX727Duxrq/W/V0cBTiiH4Guhg++/VYcGz1732qHFatZ
rp1nbMNr7ZtK/BUXmaOLat52daGFZZmJc9Zw7kAc23+gqbQQFnk6Jf9sIShJXQXOSFdqHZhLqPWp
mrA/UqIk1TxVIgfuWOTA60X2d0QOPi+ypev3RW7aGk4szhoToS29V1BVpzes5VupweVFmfH7Ukti
Qm5Lt+7LraRMG+mMvO4V8Ez774kKyGfJkdqaFU2GxS8F5afLvRXL+TxX05d7z7TFn5kYbpqWISJp
5neCS3ukXksnW+0hpjA9QpD88uv+3ooXFAgUMQUjnNg7L6Nr3p4iBGen55gWsoZv8WTPmhv2XKfx
Ls1i4IqvB/t7aUORvrdIWNZwhGVdtmUEb1vYuodFUgpa2zXCKLBNyw2ZkViObodu4jBT5yEL4sTX
eRIwL4xBu1O8vEmL7k4zTSeIfcuY+Tw0Z3Yc8RljgQ9ccXhgeQbnuqHZc8Of6zMjsObu3JrzzH9v
zu98971ra08M7fL0XHvHY+1vXaEZumYYCz1YWKb249WRZuqmrslLCVLWFVb2QMMIcPgBECfEVsc4
/b5set4wIA4ydRCVeVU2wL0sDWtWp7whzbJ4DW3U/OC3pixmuEbBmD435vqhb9u+7rm6FVh+kDiO
n1gBi3XHsRgLfS8OrcQ3XIN4KyO4fto1BxWLroHTM2UXYsGYO3Pj0Igt07LN0I8MKMuzHCvyfd+L
gPuG7YV2ZMbM9ayIJBGGzmHogzAtWL3p2jRrFFuGccj9KHSdODRCLwh8zsPQs4LQMO3EhPaDhPse
qPJwSipiWRaCu9kNy9KYtZRowBtoHtqMJ24Ymk4SeLEe+pYeMj20E9f1LTs0WBD5bhIFbIdgxpom
KxnBe68yO4qgFp3bfqKDShJBX3YY6nAmPzbAbORaRgCcm1DKypWgYIICd4KQx6ETYxoPA2a6ru1F
ISkKf8yEeSaL44TdozCr2nXNWdwMzARhGHHYzA91w/Y9FoIQbMBc5umO7ZkmwxK6601JIUuvFTf2
YWhEph8iMhAG0LYTe6HuRolvm0YSBK4JrbPINvQpiSJsFQUDJCwjjmAX27Ys04/skIWeG0dG6NsR
LG9FHgRGrE1J1OwanipFMef+IazKPNdKYAbTjEPdt7jtmH5sswgWM6xY58y3mD2l0hRl+YErhZiH
PvjWY2bFqDjgP1FocW7GPEpihzu2AyKOF0dxskOkygQFBPJhkuCSAM7BbQPKgxdaroUQ8TzDifTE
9zzTBx8+KMRlRBjID1B0APzadHA5iwgBZuJEN12fB7rtBB63wjiIbNd3IsfiOrcsK+GczJxv4Glh
c0BlDmK02ggiwdw5DE1Yx/MD7uss8EL4hWEbtpNAxCCEQMCmiFlcyIM6Z5aWsG6RJqiglO9bh57n
GnDTCP4a2rGdGC73IsSX7sbwmSBitoXziT2iscVcU4YPsJKDa0bG1COoJnaciMeATd2FfnQWssQI
XQlS0EtHMFPWBzVPMi5ym8AeRZJc13VcP4EyPO6E0DTc1XIRnYzrVhKFBo+dxNTdIPwUSYyGGcwI
oo4gGsWeGVuBHTEvsGPLdl1mIaIiPYgd5kZwU99FjPB7RKkandW8oUJPmpAiFUnMNhLTc0xuBxYC
O3BMNzQNh8c+NGAnlhvEroz1ddVUPDpA+qnWPCIL3gDKSP+2Y0RWRIbzo8S19Zibhh8YdqAb3IHk
ro0o1Qcq8KQD9bcPDjM4DOB/MWMAscAhhLHCAHijhxF8RmdJFDtGAq9k94nM8Lcr0rYnBnhFfCKS
fM5cy+bMtJCeme+DPdtzdGQD7hlIDL3uJ8SoEInaWd1lvBnYOwSu68wJWJJ4URK4iefEphEGnu27
OouZoXPTCU2u9E7cEMEZFcz4D1QuC39kURCLGAFiksRxTEComw5DHjIN17YZ7BF7ABU3iqMdYtQE
zNIWtGQUWoIYEjzM5Vh+YoaggnQNlAtDOEFsJtwyYxvoncTmDjGq+a95T8Y4dM3EDVxAPcyoI3Yd
w+JuwGGQGMnJ9ezYNU2kuB0yLb9r8Z+8ooJpiCY9coMohJ6c2LEMRDWAwLSZ5ZiOFQA2bGYCu/Rg
lxiaqVq4ug7fDPVY94OY67oRMldPEng6R31jWhzAawB7dOC/wKkJEYglrMhZToWRVJJrROjReOAh
GSI8EJfIInqEfBsxP3YZQJMZ9o75lFMFCBXnkMEskcMjiyHJAqksFNIoqyiCzDhAdCNydNMil2pg
EzR4cCphf0VGYlXsOlSLhUbCI05xBsVyxvEfxC3QwINoBnz342QQwYRcfJaV5XVXDQqPEDyGpSc6
9103MHT4kWXqoWfoBvOR/6II3YBE0THVnMp96UxST8jUse/wBIAcM0SLkeguS2zEbmST9gKfAS18
e0InTpNEUTAOLe6YVuR4bmKCRITElFg62ZyjrnCYExlIF54/lY8XN2ldFqpyI6RDsYXqR08gBzeD
yLJiDwFieDw2LZidmyhmKGqEyUaE7qqybnk9sBMbZhLCxE7MAsSCbsQBsNgJuA3lMB0gH5AjGhMq
q6wMWQYfkj5tS3dEsYa04gWobqgE9E2AuBsg8aMK9JBhjCD0UdlMKJXhb0DyGS+6nI81DfGcBFVU
jILIDiCKwwF0YZKEluWBmGWYqFV923E+Rk4lCEFN2h+uiyi3IoCQbxpRpHs6At+3PB/JBtDuub4O
HJ4ypzYbROYqKJAH5phlUkp2Et1wAEZ6ROAUcTcCKrgxFUwGVGB7O+SasqvRP5QVyaoqZ4kugFuw
ZXi24/l+zO2ERYxT7cuSAJWZo4exxSNjKq3aQJHZFJWBHZi6F7mJ79jcA4KgMETFFNg+i9C8cLg3
OpkJhXFnRTbUbcMIY5Q8KN64i0LKDK0gMhMbNRwqWoaMgxo/ED61yZOy2BxUZbYB8GazSLFDSc+D
SCaPYw/qDlGGATzBP0eWQ/0QIoP6iZG4KCNQ1IFWu+YN58jBBE3pB5V/UUQdImgtN4FINjdQ0lJl
xyEEd1Ed6EbAE3gu0xMCylse5uUHVrcHKNl53aoKCiVyHKFrQE4DJSC071LidXwojNtwTceIY+Qp
x5hWhNufs7waWs/DB/eRvw/bR6ILE/s3rzpWx6NudzS4v7e1BYmONhJjrGvXZQ0Cv+wdrVnGKraH
tplVKY0Ik9ExL1iYcRBu6w79r9wZa2SL3ZRJezwM7F3wuGnLgh+lddQBdXFFzsQelqJvWMvllq3x
b9oaQyNETfrZ5dW7s4s3x1LrTSpQYN22VbM4OEC/ve7COcDzYKBJfb/aJNtKP+yabSXX58FU6p0d
u6+TfivsDtnlUvLS/z2lqz4jLol0wYrry3VZjYQahqZiGVOx3pRd8w50To+0p+frZWdwZuTa2xV+
6oYZsGf3BN0nBzTED/trJN+uvFz2vG5/PUToq7L6O+K9GQk9DE28eCKy2Ju5L9RXyfIWXSxbLt/I
9vwBrL9jddWc1+U4BPuhaQBagruRxYr0umyucfaRPLCnhwhTHGx/PUgUiksl+Q6gDPoYC6TvCvQ3
Fl2fHj+WOJKaggvJwOTgISJBcqrgf3w93g8cxsbi2Cg4zak4r4uE10XXoKB7LJlGJAEMD4SE07Or
48t1lyQZH0PdaPQe0t9DvGOehuWOFOaXSjFaeleKy6sXF1c/nt+T4fsa5yOUCBPfGo9OZXCmEpzc
lNkluHksO4wWXi6nXHxCkD4d3d7ezjk4Iurz9lo4Wlfzk6JN25Q3P4+dbTI+BXB31055ml2jXKIS
74LfpDcsOz89PZ/IHHy5zLUkWeU50LkCX1zxtVyOuXyYCkYZecTqwVRc6OWStonDErl+DO7j0V1M
2QnCq9sUhokfy/CjlZfLKRsPyVKnqHM2O2lKjY3l2JEhL6P1WIAvZZ7oLJfDkg9HkO/p1gavr8py
kmMnw1M7oMWZhbxlO5IcfeDR+vz0mN/QhJ/Su/T66J+PZZuIiFd5DOLLZSh5a4k3hOiU0z9dNG7Z
PpiQIt3wFoH/NqUNv61mtoOfyXk/pHnOs7/XPG3QBjiPpYsdstDAwNH490OMf1yzVVmM7d6PfEY0
Yd4fHi2f3xC5Ner/WC6/XG75+HxZzGmTYVwUy4FPlsRHIA4Go/ay7eK0bL6y0TlP73hG9yWbq/I4
bQAe8bjZ2VkMFbBgsf/7oEzPqtc5WwFCV+KJgW2yn57Yzfc7fd1Llq54ffmPy8cy3UCQIGfMye7x
Q4Q8icqizDcvzsdF2WhwLJwz93YTAqAvxP8fSzRFbrnkkgPQXC4n3HxWIOOmMUaiiMPd0DL+b0IL
ktw0Qpyzgv/UnH3eIh9By1csZ4D1AyFIn8NPj3bzN0Z2G5xp1UYBGPPvyTnRg+pxwovf2N6vj9yx
KV5UNhdMfT7OuqxNRSsx2TsYBndq0fmDsuD+XtJturbprlP8vmZZml43/5HcmBOnt8Qp7S6MuP6a
vDgiJPD2dqdm60emTdNOyniHjP2hSw3TeizBtxQJSG9l4faQuucj4m5pHShSByTry7LOp2jUj3ym
gf+t/K3kHv2bSGt+ubRbisulYmL48RDHftG15VHGWf2GrVYjgabjY7GsubEr1iOX3K0kt1xiiTIi
JjIwsVzu8vRnranYfNFssi4/PTqY0qPCh9/sVrzD0E4GvefI24eGtCu6qTXWhUEJ9wuV0TOA4mfL
yp/rt7asHQw0IO1RmZX1KWvRamzlHQ1+uth7JFtv11suJ2t/vipYrd6xemyrfuQe46Ix2UmoL94e
X5y8+Nk0R5ayh13Or5CIr1ZACthry84nZaEH5OYc5XnBMp5Xac3nvFsYgWGZAmvoKdSbyfNpw9Ck
g6QHT6YivuJFWG4eKypXghrARa2+/fUFoSiJHQwUyB27pi3zly9fjL1xGNttNq33359cvZjKK7qD
n94+WpGEdR/eMf+tTIvJrqEa+FS/8bH9dbmfYX9d8R2vefZw1gkHf6xiNt1qG49+ujh9JHWfEjpL
0O/kuhLyt0x8fttC9Lk/lfTc9r3mXA1Pg0b/j+QydH6r1UZ670kRrVnRNnsfSXChYOxGMNZ36QOb
n9+r7mp+zuu82dk+lGNTm9m7LZ9rv3yp69p/aed1SferXxdJWqTto8HFe7mA3CoUHI1+fgFiiLnq
yfotHdpke3t10RXjHTY58Jm9iu85kmJBTzj/8/To/ER7iV491k6PjmoOaep/XO09ctsh2Xp4VP78
6upyXd7KZ7B/OB8JuHvmM5L+/Or4xU+vj3ckokewvlSUgeJyucPLw8W73BRHaL/GPaIa+cS+6Gn9
imUZkvk/rs5PH9tAWJ9qkPqzHfCm7Nou5MItpxyJHZk0O1fvZIx2Y4bBSSm9szOY5/gf/u0Wj18s
0jrP10QQHSA4EMb5kmzdM3YwkoPwh9Vtivq8md4tG43+8a3YvVcpUK7Z1+4uS4Z4e7S+t19e0n+4
Px6f/JTWgtNt7d8P7RYf3lSUqlzR8/3w6bOXj7bNJIkulzeCheUSjbz6NWLrM/fQLrta3Gl5RVuQ
40ibjH8i3v7OWdEd/nxzUpzlu+jxackmd2w+IWaDvNfcLpeX7/IHGopu8t/fbBiP3rsxsVMmpnmA
f1+Z4Uc7fqNmTZJeLkfsPMwFR9EWK/5Uhj9as3YnwYuh3fxuGB9L8H9KylH1cF/gl0w87ayeDfgZ
7lh2zfnJrB/f+4PcT8xufz1C5hdkxJNN9BoUdU6Cv/nB5L0d8cIdSM9mRTm7TT/Ih4dmszhtSPoZ
K5pUSIn6i9dzemCa1+J25mLvyflwpB2VKIxWGj0AsCye9C/QWJrhLyx9YQfD+zPLIi/b+DltXDIv
EkUrEGg+XxZyiRnt6T83Hc+zlsXtGuLOMpSBzzGRFUXZFRGfyZelZixap1y+6tc8R8gX4gW6Gb1T
JB85p0k5u1PXN8/NZUG3GfIy5nQqKekJv2GkTJJlAW3EFJLyqLqpBGF6KjSNuqzdCBriVai2rGcN
SlHCz+fLQrz+OCPvey53ENVIw3k8nKbH7p7/dPb6eFlI75r9q+P1RqyhBmoEjFycfs0r1jSgFz//
VvyDElDqzxp2w8Wkm5Tfkq1aBr0895fFXVjezci9xemMFauOrfhzjsK5V3BaPdfnuioFto/OzTc5
vVfxRKM41CJhz04++yjMqkFd2sR3YGjtih4H1Ho9aKzmWrvmWlnAJ1p4oBaR1Vot5FpaRFkXwzNA
/p47Ea3LMsfMRGvv02xYwve1EmfqhkhqYc3ZtYYSo1a0tDTRYMY0ScUKsCG9+ZltiPBbfjuQO4h5
wmDJRrsti7+0GqsqzmqN1JpDWHoraUMc0st0Uu7bNS+0rlrVLCZPXZKjKWKLZaFpT96tOTGmtSVW
KWINJNQrgNBB/wJeLE8LVrMSy0BU/OKt0BelrYhr6IDiTGgwJ8rSQXsjLjTxYBadaNZdG5fwdfUa
7kJb7qmIulTagJqysiFdJBorNhCnWEn2OqhUo0dkYSWtBxLygKhmSSsdYiY5bQSyyN8HQWD7BmC3
ibpGvEt2MMeqpIAXWVbeahSmtIh6klK7SZn2P+TedI3w85k6tdAIUsVUqorBDtytKSG5kkfqnClS
4BjeBPyFRYUmkU1wJSAcaQNEtmfoNbcQUo8WOBFh1VOCfjUKb60SDysRu+FGUy5B16soHE6PlP7k
HbIVdAb/YHGs1byRbkSswnGuwRJrALyER6T/kJNWYGT+r47Rm9HaKr3BtagoOq49VYsCFJ8Rdbki
vdZCADiD+6xWvF5ohJhY+22XhzArouNFsymiK9Zcw4Hra7KRuOBHsjWFaC8pXbaukX1h7xaXo4gU
wKQp+IIF9zV6bB6CkDmFbpBhaCzvCkQCXSKJXwo3hUyIlrq8SxEpHGqASCICi4E50q1i6HVCMUfX
UGzta2n7F6ivrcW0mBNEC9ffmaw9hQwwuGYKtQgxZkrShSC1G3NMeF/dFQWZMyagLSthBPGsQzPX
jvmN+q3l6WoNUKpZs94fg4jyTNJIXXdVK0elwkgxOXhTcgnjwuHE25mxDGx2U6YUWR/ngHyEfK6E
ouFd85Gj0Wvv8qLB05CzkJDqjQSXV+L5fY2qDE2OI9DytCWMyvmKhZsWGtcupap1oVyZu8X0K7La
bSo0LzwK4HM7k4R6J2uEhEkKFoGs4L4QtBK0+P2S0slhrU6E56qEoehNIOEVtJB6zUCwttB0kgKr
i1QiX4P8fy8BFWWf4p8qg6/jv2nLSrCg0sDAkiLXaIAPSvg8HhiiVXuuDN20FWMCBN6JqFD8NX95
BA5FXAiWCDG0qEMSLZBENX7Ho06geylZlhFJyWW4mt9FqHWarUQSuM6uThba1Q+vL7U3r09fXwG8
z9+8PrnUzk8uNBS2fz+52NdwkXZ1hqtOtHc/nL050c4vzo5OLi/nuxAw0YfpuEodKMbTUhQWBMQN
CRituYBkoY0BbA3oHrkmFtgiLpkBCrmEWUEKhSzkBEDDm8RnLf7A2aSToUClRF7QZWoxQVkSAfRu
gVxmJLHGGeUQqlfEhPn9q8kXVPsBs1U8orJGapbYlXaVcwcZ4F68araiWrqStXn2cZaU5JaSfMXq
kN4Uj8pMvbEpAOjj2hWhRuyoWZqaBezO0QuLImrMCcqLDj74bL/PCbtO2LuhTK9JAlpS3nwbgnPt
TGK+dHhUQWWXxQMvKZLIbaFt+W8k4UqwD0FdXVeyYrWXAizuJUnhOpLCIFtSl3mfbOVsdcVs7Jpj
C5M0ypL3fEP7iEtNvOOyL3zJZDVWIjdUjhx3eSWrRFmKaurEjE709jqmi9QEwbtgs5cAR0jzCHb2
EQUjaSPxYYUbOFnTdJyAoV3Daqu+aibQotW2XO33hpQ1giqO55IbuvQP9UTNWbTuiuum5/2IVTSa
5l2OHEufqND69oYMqclWTnKx1SvFi1KliJj7PoamoVIciQVnVM13SLr2YLHjUp7a9WmqjQj1JH15
cR9Ckpa6cCyZqBxmEVpUPsh2DFZErYLykbQH7mSBIanQpxo4NUw0R0q4lQ7TlD5VY65Wpou31S4p
kO7U93Q/TepTfrgsCt6SwRYqRaA0W5eZLDFDuvksSn3BMqomuJBKMgLbZAenzsrUEvKh2JTp7cnY
Sv0pgtVaNiv72swYGVAYTyw8a3tmVAoQqL2tY+WHiDqqh4Xk1PSIQp8mY1CxNdd+QC0IX3ouijvt
6PzHfcwFDyHi6zaN4faiVpDoOdCfCfoLzevL7m1F3gjtjK6day9iANWaZckBWmLZJsQcPqyWwqIa
bfSQg40CcZv2RsTGrcjJHaEalZgs25egSUu/Swu0hRDtqhb5ohSV9I/nxXlfh297XGozaBLtvhHN
riqqmTreaXxOVUA26Qc+mJoq9t7CDeVCVU2hopeeM8q6dmDKSc/m2rmak7F6JSYw1WwrNxErJjVb
kXQwF8RqqkwUM9RB53QfATjAajLhUZbS7o/YEqjRZ/Gm1U6vfhScNhCJxA67VqMtCGHl7XKy75j3
MJS33YxmLQS3FAAxD7vVou9l/qoZ1MOoSo66VnG+71gbuWfA+06WpilHMYiYxC1J7Whdokcl5+xb
GN43qQLcYtYyrWE3PYjSbk+/50XntvFOn7EAEnDW9hgDTuWndfqSWbRbVS3LlaZChSbKl6KMsrTS
xFzo8ZRtoENylry86TtYgn+FmQK3Zv05uWSzRYt+q2u8K3IltjWkA8iPjckNIXGtsnbXqFY/gte3
EhfUnJmcs9AqFBQ3aUbLSMxT8axWIdBmxWooqgualu3mjv3+qsmG2Ud3omSX9yIvO/LpRIKzcnFS
pdxLFMmIwln07jAM/RbZBJMvRG4ZTRaCF1z2iiGXxEKekEeKTUuRDta9Bwiji73MSZaS4tNCg/iI
TI3tsgpZIgGzGkcC+BiX+sfZZDUoxWLfRTgimO0n09+BG0t4N3XSM/kIQjNCC/EkmlhIbNyOtmJe
H4vFxEdAGhGSpE9ek6VR1wK6ck1Jp6mdhz7biTkT0UFvppnaE22FnqXZqme7uzFoaH5fRSpYb1kq
mhoAByp+aZuqrLqsd0Z1QLAvrlEQ4dN6ohieVSqqCVwpUBdaX2aKnVq5nbNQCY92n0SLJYdlvlDm
omcbhn2BeKs2cnfx7Y2doSHapsPVGpVZUo4MgiCbyW2+4cp1SYYRrMzpvaV5WgqOi7LY5NQi0OcC
aDsvarasU9+jzmvb80IEgVhstarRbMqNpWHnjgop+ozY9a58gj8E8Nnx2QL6mCkMlKmAMOGWyzqU
afT5PFqxEYxvBRBj89EWNjLPoHn1cMzio0qFPeV55UtIeuLLAQTd43JKjJdj1aFCLchNRrs8+4DH
as32NXp+TuSrdqhYgLwJRxcNEwKACsoH8myfV+SeEZvsGqk7VqN806E6Q2oTINZjhSIoLC/P92vc
s7SUdWzqFi30ANUqIRFRur6vG8iyhJe0oNgOU5P6rc/5dgF1ZrxCr81PpzyF2tK6MipGuwz9tnCb
tkqf/X7CWg0KwKCGQNWYCjBoexZlfCyKrDQZCKFShyDyngIBUN9kS4gDPYWQfWJjWcoaVcGj6GJ5
lfVHVAOAR2WrRW80eQ5+S7s9C+0XkbyRPvfF9s+vRFQU59ssOb7XIcSgQqpOY9Vg9zebROf8sYQl
8rlI0I2oJUVjRg+dg1eVbcfsy3UFD/KnRreoKCnI5LVdcaG9fPPiamF+5+07wZ2xb91Z++Z3xncx
j0oJsU/bmuMA2Prc1yUSyyPbeSarHrnfP+5rZYRTaoGO1baTqDzEvhGsFm00+cJPV/eY3Bfz9bCR
LxAHdJCpInHDp+kVNuvvMsAXZHn35KWAGrGUuH5CpBOFgvp66GhkJmqt+XaHrKxEK8jvAHyN6oOi
a3HzWtT80EiYolDdyJZZXEfyiu+NZTKLyJiRUgr6qEVqhYV7+3v8ruWF+k7fv/fkgz/bLwzG8hMu
w3GWhnfint0wApcommYyVEVTIs2/wCK3Jl8ulF92G47DSH1zbhih21VFzOrJWL2p2lI8rmmJJx37
j4psr+jqCSvI7/TshK5bhmHSAH3lUNyW98S9yCTN5OduhhlJO/nE4iqeHOWTk2sks4mg9IVL8Q2P
7djl+ZuJAik44rD/Nh592y1UHwIdXZVvoDPxbUf1S6NvOhkm7d1rqEF0w9Ft3cPPb14jjrwowv8C
l7uek7ixZ3InSvTEdL3E9rnhehF958+0tG+EdYp2oqPz47OJ9eLyvVh1d1CacTJzPbXPNi2+F0XP
+KON8s5vk95NJmy/V0jvWhj0nc79veHDOiv5QZRh/sXwZbeJ1td5OTHLZUqg8/PpRPGN4K2ZOEej
HkOhg3QlPzSp3qOgx23G35sZJu24Pw5JgnvX3NbpjmNtmJhpKlk+pJV8X8GZ273F0+31v//+v35W
AxE=
===END CRASH DUMP===

**Comment by TheNewHEROBRINEX** [comment] 2020-07-27 19:53
Duplicate of #46

**Closed by TheNewHEROBRINEX** 2020-07-27 19:53 UTC

**Comment by WEATHERCRAFTYT1** [comment] 2020-07-27 20:07
The reason I commented this was because I don’t get how to fix it
