### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BlueWhaleYT** [TheNewHEROBRINEX/Murder#51] opened 2020-03-01 03:00 UTC
Hi there,
After I had setup the arena,then I joined to the arena.The problem is coming,another player join to the arena made server crashed,it was showing "Server Closed",not "Internal Server Error".

I tried about 4-5 times then their results were same.

So therefore no such long error in console.

Thanks.

**Comment by TheNewHEROBRINEX** [comment] 2020-03-03 02:06
There must be an error in the console so please send it or you can also send me the crashdump.

**Comment by BlueWhaleYT** [comment] 2020-03-03 05:21
> There must be an error in the console so please send it or you can also send me the crashdump.

Here are the crashdump.

`PocketMine-MP Crash Dump Sat Feb 29 16:40:07 UTC 2020

Error: Nesting level too deep - recursive dependency?
File: plugins/Murder_v0.9.phar/src/TheNewHEROBRINE/Murder/MurderArena
Line: 295
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Murder v0.9

Code:
[286]     public function spawnEmerald(array $espawn) {
[287]         $this->getWorld()->dropItem(new Vector3($espawn[0], $espawn[1], $espawn[2]), Item::get(Item::EMERALD));
[288]     }
[289] 
[290]     /**
[291]      * @param Player $player
[292]      * @return bool
[293]      */
[294]     public function inArena(Player $player): bool {
[295]         return in_array($player, $this->getPlayers());
[296]     }
[297] 
[298]     /**
[299]      * @param Player $player
[300]      * @return string
[301]      */
[302]     private function getRole(Player $player): string {
[303]         return $this->isMurderer($player) ? $this->getPlugin()->translateString("game.murderer") : $this->getPlugin()->translateString("game.bystander");
[304]     }
[305] 
`

**Comment by TheNewHEROBRINEX** [comment] 2020-03-04 09:55
Duplicate of #46. By the way, the development of this plugin is currently paused indefinitely.

**Closed by TheNewHEROBRINEX** 2020-03-04 09:55 UTC
